name: Sync Fork

on:
  schedule:
    - cron: '0 */6 * * *' # Uruchamia co 6 godzin
  workflow_dispatch: # Pozwala na ręczne uruchomienie  
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Pobiera pełną historię

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/zetdou/goIT-group-project-react-node-gr4-front.git

      - name: Fetch upstream changes
        run: |
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git merge upstream/main --allow-unrelated-histories

      - name: Push changes
        run: |
          git push origin main
